# Generated by Django 4.2.16 on 2024-10-15 06:49

from django.db import migrations, models
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('link', models.URLField(max_length=100)),
                ('abstract_embeddings', pgvector.django.vector.VectorField(dimensions=384)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['abstract_embeddings'], m=16, name='all_MiniLM_L6_v2_vector_index', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
