# Generated by Django 4.2.16 on 2024-10-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0002_alter_paper_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
