# Generated by Django 4.2.16 on 2024-10-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0004_ayodhyauser_chat_message_assistantmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='message_ptr',
        ),
        migrations.DeleteModel(
            name='AssistantMessage',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
