# Generated by Django 4.2.16 on 2024-10-29 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0006_alter_message_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GloveraUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Mobile_Number', models.IntegerField()),
                ('Intake', models.CharField(blank=True, max_length=255, null=True)),
                ('NAAC_Grade', models.FloatField(blank=True, null=True)),
                ('percentage', models.FloatField()),
                ('Number_of_Backlogs', models.IntegerField(default=0, null=True)),
                ('Work_Experience', models.IntegerField(blank=True, default=0)),
                ('Bachlors_Degree', models.CharField(blank=True, null=True)),
                ('Bachlors_Specialization', models.CharField(blank=True, null=True)),
                ('University', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
