# Generated by Django 4.2.16 on 2024-10-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0007_gloverauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloverauser',
            name='NAAC_Grade',
            field=models.FloatField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gloverauser',
            name='Number_of_Backlogs',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='gloverauser',
            name='Work_Experience',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='gloverauser',
            name='percentage',
            field=models.CharField(blank=True, null=True),
        ),
    ]
