# Generated by Django 4.2.16 on 2024-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0008_alter_gloverauser_naac_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Bachlors_Degree',
            new_name='bachlors',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Bachlors_Specialization',
            new_name='bachlors_program',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Number_of_Backlogs',
            new_name='backlogs',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Mobile_Number',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='University',
            new_name='univ',
        ),
        migrations.RenameField(
            model_name='gloverauser',
            old_name='Work_Experience',
            new_name='work_exp',
        ),
        migrations.RemoveField(
            model_name='gloverauser',
            name='Intake',
        ),
        migrations.RemoveField(
            model_name='gloverauser',
            name='NAAC_Grade',
        ),
    ]
