# Generated by Django 4.2.16 on 2024-10-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angat', '0010_university_acedemicprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acedemicprogram',
            name='curriculum_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acedemicprogram',
            name='study_type',
            field=models.CharField(max_length=255),
        ),
    ]
